const statesCode = [
    {code:"AN",state:"Andaman & Nicobar Island"},
    {code:"AP",state:"Andhra Pradesh"},
    {code:"AR",state:"Arunachal Pradesh"},
    {code:"AS",state:"Assam"},
    {code:"BR",state:"Bihar"},
    // {code:"CG",state:"Chhattisgarh"},
    {code:"ND",state:"NCT of Delhi"},
    {code:"GA",state:"Goa"},
    {code:"GJ",state:"Gujarat"},
    {code:"HP",state:"Himachal Pradesh"},
    {code:"JK",state:"Jammu & Kashmir"},
    {code:"JH",state:"Jharkhand"},
    {code:"KA",state:"Karnataka"},
    {code:"KL",state:"Kerala"},
    {code:"MP",state:"Madhya Pradesh"},
    {code:"MH",state:"Maharashtra"},
    {code:"MN",state:"Manipur"},
    {code:"ML",state:"Meghalaya"},
    {code:"MZ",state:"Mizoram"},
    {code:"NL",state:"Nagaland"},
    {code:"OR",state:"Odisha"},
    {code:"PB",state:"Punjab"},
    {code:"RJ",state:"Rajasthan"},
    {code:"SK",state:"Sikkim"},
    {code:"TN",state:"Tamil Nadu"},
    {code:"TS",state:"Telangana"},
    {code:"TR",state:"Tripura"},
    {code:"UK",state:"Uttarakhand"},
    {code:"UP",state:"Uttar Pradesh"},
    {code:"WB",state:"West Bengal"},
    {code:"CG",state:"Chhattisgarh"}
]
	

export default statesCode;